version: '3'
services:
  permit-service:
    image: permit-service
    build: .
    env_file:
      - ../kdrive.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - spike-service

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db

  spike-service:
    image: drivehub.azurecr.io/meateam/spike-service:v2.0.0
    env_file:
      - ../kdrive.env
    depends_on:
      - redis
    ports:
      - '8081:8080'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
